export const GET_PRODUCTS='GET_PRODUCTS';
export const SHOW_ACTIVE_PRODUCT='SHOW_ACTIVE_PRODUCT';
export const ADD_PRODUCT_TO_CART='ADD_PRODUCT_TO_CART';
export const HIDE_ACTIVE_PRODUCT='HIDE_ACTIVE_PRODUCT';
export const REMOVE_PRODUCT_FROM_CART='REMOVE_PRODUCT_FROM_CART';
export const REMOVE_ONE_FROM_CART='REMOVE_ONE_FROM_CART';
